version: '3.5'
services:
  app:
    container_name: login-page
    image: node:16-alpine
    environment:
        NODE_ENV: development
        NODE_OPTIONS: --max_old_space_size=2048
        TZ: America/Fortaleza
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: ["yarn", "dev"]
    networks:
      - network
networks:
  network:
    driver: bridge