name: CD
on:
  workflow_dispatch:
    branches:
      - main
      - develop
      - hotfix/*
      - release/*
      - bugfix/*
      - feature/*
jobs:
  approval:
    name: AUTHORIZATION
    runs-on: ubuntu-latest
    steps:
    - name: Authorizing...
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: ${{ secrets.DEPLOY_APPROVERS }}
        minimum-approvals: 1
        issue-title: "Issue Approval"
  release:
    needs: approval
    name: RELEASE
    runs-on: ubuntu-latest
    steps:
    - name: Releasing...
      run: echo 'tag v1.0'
  deploy:
    needs: release
    name: DEPLOY
    runs-on: ubuntu-latest
    environment:
      name: Link
      url: https://josiaspires.github.io/login-page/
    steps:
    - name: Deploying...
      run: echo 'execute script'
