name: CI
on: pull_request
jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    steps:
    - name: checkout latest version
      uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: check with nodejs ^16
      uses: actions/setup-node@main
      with:
        node-version: '16.x'
    - name: install dependencies
      run: echo 'yarn install --silent'
    - name: run build
      run: echo 'yarn build'
  test:
    needs: build
    name: TEST
    runs-on: ubuntu-latest
    steps:
    - name: checkout latest version
      uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: check with nodejs ^16
      uses: actions/setup-node@main
      with:
        node-version: '16.x'
    - name: install dependencies
      run: echo 'yarn install --silent'
    - name: run test
      run: echo 'yarn test'
